"""Initial migration for workflow and billing

Revision ID: 36fc4007314c
Revises: 
Create Date: 2025-11-28 20:08:08.659391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fc4007314c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'SUBMITTED', 'SCORING', 'COMPLETED', name='assessmentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_organization_id'), 'assessments', ['organization_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('credit_type', sa.Enum('RESPONDENT_CREDIT', 'EVIDENCE_CREDIT', name='credittype'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_id'), 'credit_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_organization_id'), 'credit_ledger', ['organization_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('credit_type', sa.Enum('RESPONDENT_CREDIT', 'EVIDENCE_CREDIT', name='credittype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'CONSUMPTION', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_organization_id'), 'transactions', ['organization_id'], unique=False)
    op.create_table('respondents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respondents_email'), 'respondents', ['email'], unique=False)
    op.create_index(op.f('ix_respondents_id'), 'respondents', ['id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('answer_value', sa.JSON(), nullable=True),
    sa.Column('evidence_files', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['respondent_id'], ['respondents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    op.create_index(op.f('ix_responses_question_id'), 'responses', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_question_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_respondents_id'), table_name='respondents')
    op.drop_index(op.f('ix_respondents_email'), table_name='respondents')
    op.drop_table('respondents')
    op.drop_index(op.f('ix_transactions_organization_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_credit_ledger_organization_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_assessments_organization_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
