"""Add Project, Invitation, Evidence, and AssessmentScore models

Revision ID: 45fffc4fb965
Revises: 36fc4007314c
Create Date: 2025-11-29 05:08:54.478777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '45fffc4fb965'
down_revision: Union[str, Sequence[str], None] = '36fc4007314c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('assessment_mode', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('assessment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('layer_scores', sa.JSON(), nullable=True),
    sa.Column('veto_results', sa.JSON(), nullable=True),
    sa.Column('narrative', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyst_reviewed', sa.Boolean(), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessment_scores_id'), 'assessment_scores', ['id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('partner_email', sa.String(), nullable=False),
    sa.Column('partner_org_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='invitationstatus'), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_partner_email'), 'invitations', ['partner_email'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('virus_scan_status', sa.Enum('UPLOADING', 'UPLOADED', 'VIRUS_SCAN_PENDING', 'VIRUS_SCAN_CLEAN', 'VIRUS_SCAN_INFECTED', 'VERIFIED', 'REJECTED', name='evidencestatus'), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.add_column('assessments', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('partner_org_name', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessments', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('assessments', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('DRAFT', 'IN_PROGRESS', 'SUBMITTED', 'SCORING', 'ANALYST_REVIEW', 'COMPLETED', 'REJECTED', name='assessmentstatus'),
               existing_nullable=True)
    op.create_foreign_key(None, 'assessments', 'projects', ['project_id'], ['id'])
    op.add_column('respondents', sa.Column('name', sa.String(), nullable=True))
    op.add_column('respondents', sa.Column('seniority', sa.String(), nullable=True))
    op.add_column('respondents', sa.Column('assigned_questions', sa.JSON(), nullable=True))
    op.add_column('respondents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('responses', sa.Column('additional_context', sa.Text(), nullable=True))
    op.add_column('responses', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('responses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('responses', 'question_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('responses', 'evidence_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('evidence_files', sqlite.JSON(), nullable=True))
    op.alter_column('responses', 'question_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('responses', 'updated_at')
    op.drop_column('responses', 'submitted_at')
    op.drop_column('responses', 'additional_context')
    op.drop_column('respondents', 'created_at')
    op.drop_column('respondents', 'assigned_questions')
    op.drop_column('respondents', 'seniority')
    op.drop_column('respondents', 'name')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.alter_column('assessments', 'status',
               existing_type=sa.Enum('DRAFT', 'IN_PROGRESS', 'SUBMITTED', 'SCORING', 'ANALYST_REVIEW', 'COMPLETED', 'REJECTED', name='assessmentstatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.drop_column('assessments', 'submitted_at')
    op.drop_column('assessments', 'deadline')
    op.drop_column('assessments', 'partner_org_name')
    op.drop_column('assessments', 'project_id')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_partner_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_assessment_scores_id'), table_name='assessment_scores')
    op.drop_table('assessment_scores')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
